"""TODO only supports volume files, and incompletely at that.
"""

import datetime
import os

def write_ds(ds, filename):

    with open(filename, 'w') as f:
        f.write('# dataset file generated by write_ds.py\n')
        f.write('# last saved by %s@%s:%s\n\n' % (
                os.getenv('USER'), os.getenv('HOST'), datetime.datetime.now()))

        for key in ['volume filename',
                    'first slice Z',
                    'origin',
                    'dataset version string']:
            f.write('%s: %s\n' % (key, ds[key]))

        # TODO support alignment
        f.write('\nslices aligned: 0\n')
        f.write('slices tacked: %d\n' % len(ds['slices']))

        for slc in ds['slices']:
            f.write('begin slice tacks\n')

            for cnt in slc:
                f.write('begin %s contour\n' % cnt[0])

                for tack in cnt[1]:
                    f.write('tack: (%f,%f)\n' % tack)

            f.write('end\n\n')

        f.write('contour adjacency\n')

        for adj_slc in ds['adjacency']:
            f.write('slice\n')

            for adj_cnt in adj_slc:
                f.write('contour ')

                for adj_cnt_ind in adj_cnt:
                    f.write('%d ' % adj_cnt_ind)

                f.write('-1\n')

        f.write('\nslices labels: 0\n\n')

        f.write('slices marked: %d\n' % len(ds['markers']))

        # TODO support markers
        for mark_slc in ds['markers']:
            f.write('begin slice markers\n')
            f.write('end\n\n')

        f.write('preferences:\n\n')

        for key in ['window size',
                    'curslice',
                    'mode',
                    'scale',
                    'offset',
                    'brightnessAdjust',
                    'contrastAdjust']:
            if key in ds:
                f.write('%s: %s\n' % (key, ds[key]))

        # TODO support seeds
        f.write('\nseeded slices: 0\n')
